site_name: Lyth Docs
site_url: https://wxn0brp.github.io/Lyth
repo_url: https://github.com/wxn0brP/Lyth

theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Env: env.md
  - Readme: README.md
  - Utils: utils.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
